//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int MeetingId { get; set; }
        public string Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Message { get; set; }
        public Nullable<int> CmpId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> EmpId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual User User { get; set; }
    }
}
