//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salary()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int SalaryId { get; set; }
        public Nullable<double> Basic { get; set; }
        public Nullable<double> Allowance { get; set; }
        public Nullable<double> Medical { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> LabourWelfare { get; set; }
        public Nullable<double> Fund { get; set; }
        public Nullable<double> NetSalary { get; set; }
        public Nullable<int> CmpId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual User User { get; set; }
    }
}
